trigger:
- master
- release/*

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12
  - bash: |
      set -o errexit -o pipefail
      npm config set strict-ssl false
      npm config set //npm.nordicsemi.no/:_authToken $(WAYLAND_NPM_TOKEN_INTERNAL_PUBLISH)
      npm config set registry https://npm.nordicsemi.no/
      npm config set @babel:registry https://registry.npmjs.org/
      npm config set @cnakazawa:registry https://registry.npmjs.org/
      npm config set @jest:registry https://registry.npmjs.org/
      npm config set @serialport:registry https://registry.npmjs.org/
      npm config set @types:registry https://registry.npmjs.org/
    condition: eq(variables['Release'], 'true')
    displayName: 'Set up internal NPM registry'
  - bash: |
      set -o errexit -o pipefail
      npm i
      npm run rollup
  - bash: |
      set -o errexit -o pipefail
      npm pack
      mv *.tgz ./build/stage
    displayName: 'Pack and move package'
  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/build/stage
    displayName: 'Publish artifacts'

- job: Test
  dependsOn: [
    Build,
  ]
  pool: server
  steps:
  - task: InvokeRESTAPI@1
    displayName: Test
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'waylandJenkins'
      method: 'POST'
      urlSuffix: 'view/test/job/nrf-device-lister-js-test/buildWithParameters?BRANCH=$(Build.SourceBranch)&VSTS_URL=$(system.CollectionUri)&TOKEN=$(system.AccessToken)&PROJECT_ID=$(system.teamProjectId)&HUB_NAME=$(system.hostType)&PLAN_ID=$(system.planId)&TASK_ID=$(system.taskInstanceId)&JOB_ID=$(system.jobId)'
      waitForCompletion: 'true'
    condition: ne(variables['Build.Reason'], 'PullRequest')
